### ISSUE TITLE
Extra space in Facade config

### ISSUE THREAD

**Issue by wwwroth** [alexpechkarev/google-maps#1]
-- 'GoogleMaps' => ' GoogleMaps\Facade\GoogleMapsFacade',

There's an extra space in the value of the facade config. Took me 20 minutes to figure out why it was throwing the error: Class ' GoogleMaps\Facade\GoogleMapsFacade' not found

**Comment by alexpechkarev** [comment]
Many thanks for wwwroth!!! Fixed it locally, forget to commit. Have updated readme file now.
Regards,
Alexander
