### ISSUE TITLE
Ability to get more than 5 reviews

### ISSUE THREAD

**Issue by Donneh** [alexpechkarev/google-maps#100]
Hey,

I'm fetching place details with the following code in laravel 8.
```php
$response =  GoogleMapsFacade::load('placedetails')->setParam([
    'place_id' => 'my_place_id'
])->get();
 ```
 
 This only seems to return 5 reviews, while the place has many more.
 
 Is it possible to get all reviews of a given place?

**Comment by alexpechkarev** [comment]
Hi @Donneh,

According to the [Place Details response](https://developers.google.com/maps/documentation/places/web-service/details#Place-reviews) documentation  you will only get up to five reviews. You can order results by  `most_relevant` or `newest`.
