### ISSUE TITLE
Get administrative_area_level_4

### ISSUE THREAD

**Issue by dekyuda** [alexpechkarev/google-maps#103]
How to get only administrative area level 4 with this library ?
Thanks

**Comment by alexpechkarev** [comment]
Hi @dekyuda,

You can pass an optional `result_type` parameter with `administrative_area_level_4` value.

See [Reverse geocoding requests](https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding#reverse-requests) for more details. According to the documentation not all nations exhibit these administrative levels.

```php
    $rsp = \GoogleMaps::load('geocoding')
    ->setParamByKey('latlng', '53.793066,-3.05577')
    ->setParamByKey('result_type', 'administrative_area_level_4')
    ->get('results');  
```
