### ISSUE TITLE
  Non-static method GoogleMaps\GoogleMaps::load() cannot be called statically

### ISSUE THREAD

**Issue by enterlight** [alexpechkarev/google-maps#107]
The following line of code 
```
        $response = GoogleMaps::load('timezone')
            ->setParam([
                'location' => [
                    'lat'  => -33.8669710,
                    'lng'  => 151.1958750
                ],
            ])
            ->get();
``` 

Generates the following error
```
  Non-static method GoogleMaps\GoogleMaps::load() cannot be called statically
```

```
        "php": ">=8.1",
        "laravel/framework": "^9.21",
...
        "alexpechkarev/google-maps": "^9.0",
```

I have added the alias and the provider... Not sure what is going on.

**Comment by enterlight** [comment]
Nevermind mate.   I was not using the facade.  You can close this one.  Sorry for the trouble

**Comment by YanisariGazi** [comment]
What I know is how to eliminate Non-static method errors like this

`    protected $gMaps;
     public function __construct(GoogleMaps $gMaps){
             $this->gMaps = $gMaps;
     }
     
     public funtion maps(){
     $response = $this->gMaps->load('geocoding')
            ->setEndpoint('json')
            ->getEndpoint();
     dd( $response);
     }
`
