### ISSUE TITLE
How to Get Specific area

### ISSUE THREAD

**Issue by tayyabzino19** [alexpechkarev/google-maps#108]
I have provide lat & lng details now how can i only get hospital and school details

**Comment by alexpechkarev** [comment]
Hi @tayyabzino19,

You can try filtering out one or more result types

```php
    $rsp = \GoogleMaps::load('geocoding')
    ->setParamByKey('latlng', '40.714224,-73.961452')
    ->setParamByKey('result_type', 'street_address')
    ->get('results');  
```
Here is the [Reverse geocoding requests ](https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding#reverse-requests)details.

For the above example the response will only return one address.

```php
array:1 [
  "results" => array:1 [
    0 => array:6 [
      "address_components" => array:8 []
      "formatted_address" => "277 Bedford Ave, Brooklyn, NY 11211, USA"
      "geometry" => array:3 []
      "place_id" => "ChIJd8BlQ2BZwokRAFUEcm_qrcA"
      "plus_code" => array:2 []
      "types" => array:1 []
    ]
  ]
]
```
