### ISSUE TITLE
Get photo URL using `placephoto`

### ISSUE THREAD

**Issue by airtonjr** [alexpechkarev/google-maps#109]
Hello!

Great work here!

I have a question. If I am using:

```
$photoUrl = config('googlemaps.photos_url') . '?maxwidth=400&photo_reference=' . $photoReference . '&key=' . config('googlemaps.key');
            $response = Http::get($photoUrl);

            return $response['url'];
```

I am able to get the `URL` for the image but if I am using:
```

$photoUrl = GoogleMaps::load('placephoto')
            ->setParam(['photoreference' => MY_PHOTO_REFERENCE])
            ->get('url');

        return $photoUrl;

```

Is not possible. Is there something different that I should be doing?

Thank you!

**Comment by alexpechkarev** [comment]
Hi @airtonjr,

Thank you for your question.

You do not need to make an API call to obtain the image URL.

Here is the image URL

```php
$photoUrl = config('googlemaps.service.placephoto.url') 
   . 'maxwidth=400&photo_reference=' 
   . $photoReference 
   . '&key=' 
   . config('googlemaps.key');
```

The `->get()` method in this case will return the image content.
