### ISSUE TITLE
Laravel 10 : tag a version

### ISSUE THREAD

**Issue by paceband** [alexpechkarev/google-maps#111]
Laravel 10 seems to be done only on master branch.
Tag a version please.

**Comment by alexpechkarev** [comment]
The Laravel 10 tag version has been released, thanks!

**Comment by paceband** [comment]
It seems not to be working... Not sure what's going on...
Getting:
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires alexpechkarev/google-maps ^10.0, found alexpechkarev/google-maps[dev-master, dev-add-code-of-conduct-1, 1.0, ..., 1.0.9, 5.1, ..., 5.8.x-dev, 6.0.0, 7.0.0, 7.1, 8.0, 8.0.x-dev (alias of dev-master), 9.0] but it does not match the constraint.
---
You could also upgrade phpunit:
"phpunit/phpunit": "^10.0"

**Comment by alexpechkarev** [comment]
Hi @paceband, thank you for picking this up. Please can you try again?

**Comment by paceband** [comment]
> Hi @paceband, thank you for picking this up. Please can you try again?

Works fine. Thanks.
