### ISSUE TITLE
Add api (curl) request logging, behind APP_DEBUG=true or similar config options

### ISSUE THREAD

**Issue by emjayess** [alexpechkarev/google-maps#115]
I've been using this just a few weeks, and have a need for greater visibility / observability into the raw Api requests that are being initiated against the api.

So, for instance, propose a need for curl logging the request and perhaps enable conditionally based on `APP_DEBUG`, or a similar flag in `config/googlemaps.php`.

**Comment by lrljoe** [comment]
What specifically are you looking to log?

**Comment by emjayess** [comment]
Ah, I am primarily utilizing the distancematrix and geocoding, maybe soon also directions – and distancematrix in my use cases is almost always a single origin and single destination. At least at this point have not been presenting maps.. thus far, I'm just sprinkling the distance and duration text results out to the UI.

Out of the gate I have been seeing some like ZERO_RESULTS, NOT_FOUND, or just obviously unexpected distances and durations... seeming to indicated a mangled address or improperly sanitized/supplied-by-my-code addresses..

> What specifically are you looking to log?

For the generated Api requests & responses, and when I am desiring better visibility into what's going on, I guess I'd like to capture as much instrumentation as possible. I have even considered creating a table (and a migration and model, in Laravel) around these, toward the ends of being able to track improvements in results and cleaning up this data and implementation over time.

**Comment by alexpechkarev** [comment]
Hi @emjayess 

Apologies for the late response.

Can you please propose the changes and create a pull request?

**Comment by lrljoe** [comment]
IMHO - not a bug/issue.  Is just a lack of understanding of how the internet works.
