### ISSUE TITLE
Pass an array of waypoints to directions

### ISSUE THREAD

**Issue by damm1991** [alexpechkarev/google-maps#12]
hello,

i want to pass an array of waypoints to the directions service but it is not working.
even converting the array to a string does not work.

when i use: 'waypoints'       =>  [$array]',  it is not working, even when array is a string like: 'Vancouver BC', 'Seattle'.

But when i type this, and not use a variable, it does work.

Can you help me?

**Comment by alexpechkarev** [comment]
Hi damm1991,

Please can you send your code example and data you using ?

Thanks,
Alexander
