### ISSUE TITLE
FatalErrorException in compiled.php line 5301:

### ISSUE THREAD

**Issue by cp-black** [alexpechkarev/google-maps#13]
Hi,

I'm currently working on a project that involves google maps turn by turn directions.

I encounter this error, what could be the cause of this?

Call to undefined method Illuminate\Support\Facades\GoogleMapsFacade::load()

I placed the GoogleMapsFacade.php to Illuminate\Support\Facades\ directory.

Thanks in advance.

**Comment by alexpechkarev** [comment]
Hi Mel,

Please ensure you have registered package in `config/app.php`

```php
'providers' => [
    ...
    'GoogleMaps\ServiceProvider\GoogleMapsServiceProvider',
]

'aliases' => [
    ...
    'GoogleMaps' => 'GoogleMaps\Facade\GoogleMapsFacade',
]
```

Than simply call package method as:

```php
$response = \GoogleMaps::load('geocoding')
        ->setParam (['address' =>'santa cruz'])
        ->get();
```

Let me know if you have any issues.
Regards,
Alexander

**Comment by cp-black** [comment]
Hi alex,

Please correct me if i'm wrong, i should place the "GoogleMaps" folder outside the "app" folder
then place the "Facade" & "ServiceProvider" which contains the "GoogleMapsServiceProvider.php" and  "GoogleMapsFacade.php" i have already registered the facade and provider in config/app.php and now i have this error message 

"Class 'GoogleMaps\ServiceProvider\GoogleMapsServiceProvider' not found"

My File directory is
- app
- GoogleMaps
    - Facade
        - GoogleMapsFacade.php
    - ServiceProvider
       - GoogleMapsServiceProvider.php

**Comment by alexpechkarev** [comment]
Hi Mel,

The easiest way to install the package is using composer, as it automatically install it, including package dependencies, in this case `alexpechkarev/geometry-library`. New files are stored `vendor` folder.

in console simply issue following command: 

`composer require alexpechkarev/google-maps:1.0.5`

Alternative way is to open `composer.json` file and add following lines:

```json
	"require": {
               "laravel/framework": "5.*",
                "alexpechkarev/google-maps": "1.0.5"
	},
```
and in console issue following command: `php composer update`

Do not forget to register service providers and facades in `config/app.php`
Also you would need to publish package config file `php artisan vendor:publish --tag=googlemaps --force`

Let me know if above helps.
Regards,
Alexander

**Comment by cp-black** [comment]
Hi Alex,

Finally! haha thanks i got it to work. i dont know what i have done wrong so what i did is reinstall my composer and create a fresh laravel app.

Thanks!
Best Regards, 
Mel Bulan

**Comment by alexpechkarev** [comment]
Hi Mel,

Great new, glad that all worked out.
Let me know if you have any questions.

Will close this thread for now.

Regards,
Alexander
