### ISSUE TITLE
[Help] Use Case

### ISSUE THREAD

**Issue by KayTokyo** [alexpechkarev/google-maps#14]
Can i use this to add a map to my view which shows a location based on postcode. 

If so can you give me an example on how i can do this. (I have the package configured and setup already)

thank you in advance.

**Comment by alexpechkarev** [comment]
Hi KayTokyo,

You can geocode your postcode to latitude and longitude using this package.
Than use following, as per [this example](https://developers.google.com/maps/documentation/javascript/examples/marker-simple), to show Google Map with marker for your postcode.

```
    <div id="map"></div>
    <script>

      function initMap() {
        var myLatLng = {lat: -25.363, lng: 131.044};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
    </script>
```
