### ISSUE TITLE
webservice:268 error

### ISSUE THREAD

**Issue by tengju** [alexpechkarev/google-maps#15]
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Can't use function return value in write context' in /var/www/'user'l/httpdocs/laravel/vendor/alexpechkarev/google-maps/src/WebService.php:268

Hi i just started using laravel as framework and am almost done with my project with it. I have a problem with the google-maps. Everytime i try this code

`
        $response = \GoogleMaps::load('geocoding')->setParam (['address' =>'santa cruz'])->get();
`
 I get the error thats written above.
If you can please help me with this issue ill be really grateful.

**Comment by alexpechkarev** [comment]
Hi,

Please check that you have publish package config file, if not simply use `php artisan vendor:publish --tag=googlemaps --force` 
or copy package configuration file and paste into config/googlemaps.php.

Also please ensure you have added service key in the config file.

Regards,
Alexander

**Comment by tengju** [comment]
Hi,

I followed the instructions.
I tried the ` php artisan vendor:publish --tag=googlemaps --force `
i copy pasted the package configuration file and paste into config/googlemaps.php.
And i also have added the service key in the config file.

unfortunately nothing worked. any other reasons or suggestions that may help?

**Comment by tengju** [comment]
I have to apologize. I was using PHP 5.4 and thought that enough but it seems that the empty() function doesnt work the same as in PHP 5.6. Thanks for all the help it works now great script ty.

**Comment by alexpechkarev** [comment]
Great that all resolved, thanks!
