### ISSUE TITLE
duration_in_traffic Response / Directions API

### ISSUE THREAD

**Issue by realtarget** [alexpechkarev/google-maps#18]
Hi Alex,

is it possible to make a signed request to google (directions api) in order to get the duration_in_traffic response? I'm building a dashboard for my family to show how long everybody needs to get to work, school etc.

Best regards,
Rene

**Comment by realtarget** [comment]
Sorry, it works - was a bit late yesterday evening ;-)

**Comment by alexpechkarev** [comment]
Hi @realtarget,

Thank you for your updates, glad that all worked out for you.

Regards,
Alex

**Comment by realtarget** [comment]
Like a charm Alex, thanks for this great and easy-to-use laravel extension.
