### ISSUE TITLE
Decode Polyline point returned by Google Directions API

### ISSUE THREAD

**Issue by manzoor-ahmed** [alexpechkarev/google-maps#2]
Hi
I just installed your library and it looks pretty cool. Just wondering if there is any method to decode the polyline point returned in Directions response.  Here is Directions API response:
```
{
   "geocoded_waypoints" : [
      {
         "geocoder_status" : "OK",
         "place_id" : "ChIJlfTBINcEGTkR_Wu1RAUpDYI",
         "types" : [ "street_address" ]
      },
      {
         "geocoder_status" : "OK",
         "place_id" : "ChIJlfTBINcEGTkR_Wu1RAUpDYI",
         "types" : [ "street_address" ]
      }
   ],
   "routes" : [
      {
         "bounds" : {
            "northeast" : {
               "lat" : 31.5562273,
               "lng" : 74.3571711
            },
            "southwest" : {
               "lat" : 31.55462439999999,
               "lng" : 74.3546016
            }
         },
         "copyrights" : "Map data ©2015 Google",
         "legs" : [
            {
               "distance" : {
                  "text" : "0.3 km",
                  "value" : 302
               },
               "duration" : {
                  "text" : "1 min",
                  "value" : 45
               },
               "end_address" : "132 Allama Iqbal Road, Lahore, Pakistan",
               "end_location" : {
                  "lat" : 31.5562273,
                  "lng" : 74.3546016
               },
               "start_address" : "132 Allama Iqbal Road, Lahore, Pakistan",
               "start_location" : {
                  "lat" : 31.55462439999999,
                  "lng" : 74.3571711
               },
               "steps" : [
                  {
                     "distance" : {
                        "text" : "0.3 km",
                        "value" : 302
                     },
                     "duration" : {
                        "text" : "1 min",
                        "value" : 45
                     },
                     "end_location" : {
                        "lat" : 31.5562273,
                        "lng" : 74.3546016
                     },
                     "html_instructions" : "Head \u003cb\u003enorthwest\u003c/b\u003e on \u003cb\u003eAllama Iqbal Rd\u003c/b\u003e",
                     "polyline" : {
                        "points" : "k_r_Ei{ydM[r@e@bAOZWh@Ub@]p@c@`AU^e@p@cAxA"
                     },
                     "start_location" : {
                        "lat" : 31.55462439999999,
                        "lng" : 74.3571711
                     },
                     "travel_mode" : "DRIVING"
                  }
               ],
               "via_waypoint" : []
            }
         ],
         "overview_polyline" : {
            "points" : "k_r_Ei{ydMiB|Ds@tAy@`BiBjC" // this is the encoded polyline point to decode
         },
         "summary" : "Allama Iqbal Rd",
         "warnings" : [],
         "waypoint_order" : []
      }
   ],
   "status" : "OK"
}
```
I already decoded the **point** in JS, I need your help to do same using this library.

Thanks

**Comment by alexpechkarev** [comment]
Hi Manzoor,

Thank you for your comment. I have added new method get_pld() that uses emcconville/google-map-polyline-encoding-tool package to decode polyline. Update this package version to 1.0.1. It is not great structured at the moment but works for me. Let me know what you think.
Regards,
Alexander

**Comment by manzoor-ahmed** [comment]
Hi Alexander
Thanks for adding ```get_pld()``` it worked :+1: . While I was working on localhost, I was getting ```SSL certificate problem: unable to get local issuer certificate``` exception. I just forked your library and updated ```googlemaps.php``` configurations file and main ```GoogleMaps.php``` and now its working perfectly.

Actually, I want to do something like JS below
```
// ver result; being the response of Directions API
var pointLatLng = new google.maps.LatLng(31.555072365811778, 74.35535565554198);
    var polyLine = new google.maps.Polyline({
      path: google.maps.geometry.encoding.decodePath(result.routes[0].overview_polyline.points)
    });
    var pointResult = google.maps.geometry.poly.isLocationOnEdge(pointLatLng, polyLine, 10e-4); 
    if (pointResult) {
      console.log("The point is on route!");      
    } 
```
As of now I've decoded polyline, but how do i call Google Maps functions (above) in this library?

**Comment by alexpechkarev** [comment]
Hi Manzoor,
Glad to hear that it's working as expected. Will apply "ssl_verify_peer"  changes you have made to the library. 
If you use get_pld() method instead of get() than result.routes[0].overview_polyline.points will contain decoded array of points.

With regards to you question: will it worth expanding library by adding extra methods like `containsLocation()` and `isLocationOnEdge`  as per https://developers.google.com/maps/documentation/javascript/geometry?hl=en#poly

Will it be useful? 
```php
\GoogleMaps::load('directions')
                 ->setParam([... ]) 
                 ->isLocationOnEdge('31.555072365811778, 74.35535565554198');

\GoogleMaps::load('directions')
                 ->setParam([... ]) 
                 ->containsLocation('31.555072365811778, 74.35535565554198');
```

**Comment by manzoor-ahmed** [comment]
@alexpechkarev It would be awesome to have functions like you mentioned. Please add a third parameter to ```isLocationOnEdge($lat, $lng, $tolerance)``` as mentioned in the documentation
https://developers.google.com/maps/documentation/javascript/geometry#isLocationOnEdge

**Comment by alexpechkarev** [comment]
Hi Manzoor,

Will have to restructure the code, to keep it simple and modularized. Will update you on this.
Regards,
Alexander

**Comment by alexpechkarev** [comment]
Hi Manzoor,

The requested changes have been applied, please update package to version 1.0.2. The `get_pld()` method has been removed.

New things that have been added:
 - package now requires alexpechkarev/geometry-library: 1.0.0 
 - config file for direction service has new key:
'decodePolyline'        =>  true, // true = decode overview_polyline.points to an array of points

- new methods available with Directions service
-- isLocationOnEdge( $lat, $lng, $tolrance = 0.1)
--containsLocation($lat, $lng)

Here is how to use it:
```php
             $rsp =   \GoogleMaps::load('directions')             
                    ->setParam([
                        'origin'          => 'place_id:ChIJ685WIFYViEgRHlHvBbiD5nE', // required
                        'destination'     => 'place_id:ChIJA01I-8YVhkgRGJb0fW4UX7Y', //required
                      ])
                  ->isLocationOnEdge(56.3957113,-3.4307818);
dd($rsp); // false

             $rsp =   \GoogleMaps::load('directions')             
                    ->setParam([
                        'origin'          => 'place_id:ChIJ685WIFYViEgRHlHvBbiD5nE', // required
                        'destination'     => 'place_id:ChIJA01I-8YVhkgRGJb0fW4UX7Y', //required
                      ])
                   ->containsLocation(55.86483,-4.25161);

 dd($rsp); // true 

```
Let me know how is it working for you.
Will update Readme soon.
Regards,
Alexander

**Comment by manzoor-ahmed** [comment]
Hey Alexander 
Thanks a lot. You saved my time. I'll let you know about new updates. 

Thanks again.
Manzoor
