### ISSUE TITLE
 composer dump-autoload -o 

### ISSUE THREAD

**Issue by KillWil** [alexpechkarev/google-maps#22]
Hello,

I experienced this issue running laravel 5.3 project

**PHP Fatal error:  Class 'GoogleMaps\ServiceProvider\GoogleMapsServiceProvider' not found**

I add these lines to config/app.php

```
--> Providers

GoogleMaps\ServiceProvider\GoogleMapsServiceProvider::class,

--> Alias

'GoogleMaps' => GoogleMaps\Facade\GoogleMapsFacade::class,

```

Composer update is running fine and install your library with no issue.

I try  
```composer dump-autoload -o```
No luck with this

Have an idea ?
Thanks a lot

**Comment by alexpechkarev** [comment]
Hi @KillWil,

Please ensure that package has been installed.
Have successfully installed on fresh Laravel 5.3, let me know if you have any issues.

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "alexpechkarev/google-maps": "1.0.7"
    },
```

**Comment by KillWil** [comment]
Hello Alex,

I found my problem...
I forgot to deploy the GoogleMaps config file...

This is why I've got this error, it works fine now !
Thanks
