### ISSUE TITLE
Is it working with Lumen 5.x?

### ISSUE THREAD

**Issue by diegoflorez** [alexpechkarev/google-maps#23]
Thanks for this great package to manage google APIs, I am wondering if it works with Lumen?

**Comment by alexpechkarev** [comment]
Hi @diegoflorez,

Didn't tested with Lumen,  have you installed the package ?

Regards,
Alexander

**Comment by diegoflorez** [comment]
Yes I did, but in laravel 5.2, I'll try it on Lumen and let you know.
