### ISSUE TITLE
json_decode fails to parse the response

### ISSUE THREAD

**Issue by prashant0710** [alexpechkarev/google-maps#25]
I have been trying to do the following
 public function index()
    {
    	$d =   \GoogleMaps::load('directions')->setEndpoint('json')
                    ->setParamByKey('origin', 'Bengaluru')
                    ->setParamByKey('destination', 'Kolkata')->get();

                 //   echo $d;
$json_a= json_decode($d,true); 
echo $json_a->geocoded_waypoints[0]->geocoder_status;
But I am not getting any values .Can anyone please help me out

**Comment by alexpechkarev** [comment]
Hi @prashant0710 ,

Please can you show output of your `$json_a` ?
