### ISSUE TITLE
Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by Elfo404** [alexpechkarev/google-maps#32]
Can you please update the package.json to add laravel 5.5 compatibility?

**Comment by alexpechkarev** [comment]
Hi @Elfo404 ,

Thank you for your question.

Do you mean **`composer.json`**, please can you clarify ?

Current package specifies requirements as follow:

```
...
	"require": {
		"illuminate/support": "5.*",
		"alexpechkarev/geometry-library" : "1.0.0"
	},
....
```

Regards,
Alexander

**Comment by Elfo404** [comment]
Sorry, my bad,i had issues with another package and i misread the composer error message.

Thank you!
