### ISSUE TITLE
alternatives=true to get other itinary 

### ISSUE THREAD

**Issue by mourareaupro** [alexpechkarev/google-maps#33]
Hello i would like to get the shortest way from a point A to a point B and not the fastest. So i looked around on the forums and i found alternatives=true param who gives you different alternatives. 

How could i check the differents way ? actually i have this in my controller to calculate the distance * 2. I simply whould like to check if there is a shortest way and if it is i get the shortest way. hope you could help me. thanks a lot in advance 

`$origin = $licencie->lb_adresse .' '. $licencie->lb_ville_naissance .' '. $licencie->cd_dept_naissance;
$destination = $rencontre->stade->adresse_stade .' '. $rencontre->stade->ville_stade .' '. $rencontre->stade->cd_post_stade;

        $response = \GoogleMaps::load('directions')
            ->setParam([
                'origin'          => $origin,
                'destination'     => $destination,
                'mode' => 'driving' ,
                //'alternatives' => true,
                'language' => 'fr',

            ])->get();

        $parsed_json = (json_decode($response));

        $result = $parsed_json->{'routes'}[0]->{'legs'}[0]->{'distance'}->{'text'};

        $a = $result;
        $b = str_replace(" km",'',$a);
        $distance = str_replace(",",'.',$b);

        //distance * 2 
        $distance = $distance * 2 ;`

**Comment by alexpechkarev** [comment]
Hi @mourareaupro,

With Directions Request you may use use waypoints with ```optimizeWaypoints: true```,  [this to allow the Directions service to optimize the provided route by rearranging the waypoints in a more efficient order.](https://developers.google.com/maps/documentation/javascript/directions#Waypoints) 

`  waypoints[]: DirectionsWaypoint,
  optimizeWaypoints: Boolean,`

Hope this helps,
Regards,
Alexander
