### ISSUE TITLE
Incompatibility of params with non ASCII characters

### ISSUE THREAD

**Issue by dnmarques** [alexpechkarev/google-maps#34]
Hello,

I'm trying to do a search with geocoding library for the locality "P**ó**voa de Santa Iria, Portugal".
What is happening is that params are being encoded 2 times, and because of portuguese characters, url is distorted and no results are found. 

Here is the difference:
Url by hand:
`https://maps.googleapis.com/maps/api/geocode/json?key=[key]&components=locality:Póvoa de Santa Iria, Portugal`

With the package it becomes
`https://maps.googleapis.com/maps/api/geocode/json?key=[key]&components=locality%3AP%25C3%25B3voa%2Bde%2BSanta%2BIria,%2BPortugal`

**Comment by alexpechkarev** [comment]
Just merged your changes, thanks!
