### ISSUE TITLE
create polygon and check point in polygon

### ISSUE THREAD

**Issue by mohammad6006** [alexpechkarev/google-maps#37]
in my food delivery system i need to divide city to multiple zone and set price of each zone for delivery system

can  I use this package to create polygon and check user location is in any polygons?

**Comment by alexpechkarev** [comment]
Hi @mohammad6006 ,

You can try following method from this package:
isLocationOnEdge( $lat, $lng, $tolrance = 0.1 ) - To determine whether a point falls on or near a polyline, or on or near the edge of a polygon, pass the point, the polyline/polygon, and optionally a tolerance value in degrees.

This method only available with Google Maps Directions API.
