### ISSUE TITLE
header is not json

### ISSUE THREAD

**Issue by mohammad6006** [alexpechkarev/google-maps#38]
```
$response->setEndpoint('json')->get();
```
return json with **html** header

and I have to use :
```
return response($response)->header('Content-Type', 'application/json');
```
to set header

**Comment by alexpechkarev** [comment]
Hi @mohammad6006,

Thank you for your question.

The response from Google Maps API call, if not explicitly set, is `json` by default.

As per [Laravel documentation](https://laravel.com/docs/5.4/responses#json-responses), you would use following to return `json` response

`return response()->json([
    'name' => 'Abigail',
    'state' => 'CA'
]);` 

In your case use following:

```
$response = \GoogleMaps::load('geocoding')
		->setParam (['address' =>'santa cruz'])
 		->get();

return response()->json([$response]);
```
