### ISSUE TITLE
containsLocation not work

### ISSUE THREAD

**Issue by messi89** [alexpechkarev/google-maps#39]
I test the doc example but it always return false, is there any thing wrong ?

`$response = \GoogleMaps::load('directions')
            ->setParam([
                'origin'          => 'place_id:ChIJ685WIFYViEgRHlHvBbiD5nE', 
                'destination'     => 'place_id:ChIJA01I-8YVhkgRGJb0fW4UX7Y', 
            ])
           ->containsLocation(55.86483,-4.25161);

    dd( $response  );  // true`

I try my api key with google example here https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation it work

**Comment by messi89** [comment]
finaly I used isLocationOnEdge with tolerance in meters

problem solved

**Comment by alexpechkarev** [comment]
Glad to hear, thanks!
