### ISSUE TITLE
php artisan vendor:publish --tag=googlemaps --force =­> Does not work

### ISSUE THREAD

**Issue by paceband** [alexpechkarev/google-maps#4]
php artisan vendor:publish --tag=googlemaps --force
does not create any file in config.
Work around: I had to copy it manually

**Comment by alexpechkarev** [comment]
Hi paceband,

Not sure why `php artisan vendor:publish --tag=googlemaps --force` wasn't working for you, please can check Laravel version you using ?

Have tested locally on Laravel Framework version 5.0.33, got following output.
Copied File [/vendor/alexpechkarev/google-maps/src/config/googlemaps.php] To [/config/googlemaps.php]
Publishing Complete!

If it didn't work for some reason, as you mentioned copy and paste is the backup plan :)
Regards,
Alexander

**Comment by paceband** [comment]
Hi,
I use the latest 5.1 Laravel version... 5.1 vs 5.0... That might be my problem.
I might also explain why, when I you your test case, I receive this error:
Class 'GoogleMaps' not found
Any plan to migrate to 5.1? (I might do the work to make it work in 5.1)

**Comment by paceband** [comment]
Ok... I've just found out what's going on.
Typing this command solved my issue:
php artisan config:clear
Just works great on the latest Laravel 5.1! :-)
Thanks for this great Package which will save me so much work!

**Comment by alexpechkarev** [comment]
Many thanks for confirming paceband, glad to hear that package is useful :)
Regards,
Alex

**Comment by facundofarias** [comment]
Hello @alexpechkarev,
I have Laravel 5.4 and this isn't working anymore.
Any ideas?

**Comment by alexpechkarev** [comment]
Haven't tested with Laravel 5.4. Can you provide more details ?
