### ISSUE TITLE
Php 7.2 incompatibility

### ISSUE THREAD

**Issue by m00n71ght** [alexpechkarev/google-maps#40]
Have this exception running php 7.2 laravel 5.5
>`ErrorException count(): Parameter must be an array or an object that implements Countable`

> /vendor/alexpechkarev/google-maps/src/WebService.php:305 
```php

// Validate Endpoint
if(!array_key_exists('endpoint', config('googlemaps') )
        || !count(config('googlemaps.endpoint') < 1)){
    throw new \ErrorException('End point must not be empty.');
}

```

**Comment by alexpechkarev** [comment]
Hi @m00n71ght,

Please see this issue [Laravel not compatiable with php 7.2](https://github.com/laravel/framework/issues/20248) 

I can suggest explicitly cast to an array in config file:

` 
    'endpoint' =>(array)[
        'xml'           => 'xml?',
        'json'          => 'json?',
    ],`

**Comment by m00n71ght** [comment]
Thanks a lot!

**Comment by vesper8** [comment]
@alexpechkarev I tried your solution

In my googlemaps.php config file I have 

```
    /*
    |--------------------------------------------------------------------------
    | End point
    |--------------------------------------------------------------------------
    |
    |
    */

    'endpoint' => (array)[
        'xml'           => 'xml?',
        'json'          => 'json?',
    ],
```

At the very bottom

But I am still getting the same error 

```
Parameter must be an array or an object that implements Countable at /home/forge/develop.nomadsoulmates.com/current/vendor/alexpechkarev/google-maps/src/WebService.php:305)
```

I did make sure to clear all caches and config cache... how come this worked for @m00n71ght but not for me?

Am also running PHP 7.2

**Comment by vesper8** [comment]
Ok.. figured it out.. there's a syntax error in the code above.. look at the parentheses of the count, it's wrapping the whole expression and not only the array

```
count(config('googlemaps.endpoint') < 1)
```

should be

```
count(config('googlemaps.endpoint')) < 1
```

After fixing this bug though it is now throwing the error even though my endpoint array does have a count of 2

I think the logic is pretty confusing.. I changed it to this on mine:

```
            if( ! (array_key_exists('endpoint', config('googlemaps') )
                    && count(config('googlemaps.endpoint')) > 0 ) ) {
                throw new \ErrorException('End point must not be empty.');
            }
```

This is working now for me.. going to make a pull request
