### ISSUE TITLE
PHP 7.2 ErrorException : count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by PeteButler** [alexpechkarev/google-maps#43]
Hi, under PHP 7.2 WebService.php line 305 throws an error exception when uses the count() function, and could do with a guard to ensure the config key variable is an instance of countable

**Comment by iRayops** [comment]
This the original code:
            `// Validate Endpoint
            if(!array_key_exists('endpoint', config('googlemaps') )
                    || !count(config('googlemaps.endpoint') < 1)){
                throw new \ErrorException('End point must not be empty.');
            }`

I think you should delete " ! " and change the " < 1 " out of the count() function:
            `// Validate Endpoint
            if(!array_key_exists('endpoint', config('googlemaps') )
                    || count(config('googlemaps.endpoint')) < 1){
                throw new \ErrorException('End point must not be empty.');
            }`

At least work for me!

**Comment by alexpechkarev** [comment]
Hi @PeteButler ,

Please pull latest version, changes has been applied a while ago with regards to the [similar issue](https://github.com/alexpechkarev/google-maps/issues/40).

Regards,
Alexander

**Comment by PeteButler** [comment]
Hi @alexpechkarev, many thanks for the rapid response
