### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by i-mighty** [alexpechkarev/google-maps#45]
Please update README.md file
Change
'providers' => [
    ...
    'GoogleMaps\ServiceProvider\GoogleMapsServiceProvider',
]

'aliases' => [
    ...
    'GoogleMaps' => 'GoogleMaps\Facade\GoogleMapsFacade',
]
To
'providers' => [
    ...
   GoogleMaps\ServiceProvider\GoogleMapsServiceProvider::class,

'aliases' => [
    ...
   GoogleMaps' => GoogleMaps\Facade\GoogleMapsFacade::class,
]
This is very misleading for people who would just copy the code and paste in their file. Awesome project.

**Comment by alexpechkarev** [comment]
Hi @i-mighty,

The README.md file has been updated with your suggestion.

Thanks,
Alexander
