### ISSUE TITLE
is it possible to make it run on a php environment without any farmework?

### ISSUE THREAD

**Issue by WongYueKeung** [alexpechkarev/google-maps#46]
I am using framework ThinkPHP 5.1, I wish I can run this package on this farmwork as well..plz

**Comment by alexpechkarev** [comment]
Hi @WongYueKeung 

You should be able to use this package outside of the Laravel, however there are a couple of changes required:
WebService.php
Line 86: replace 
`$this->endpoint = array_get(config('googlemaps.endpoint'), $key, 'json?');`
with 
`$this->endpoint = 'json';`

In Directions.php and WebService.php files 
Replace all reference to [array_get](https://laravel.com/docs/5.2/helpers#method-array-get), [array_set](https://laravel.com/docs/5.2/helpers#method-array-set), [array_dot](https://laravel.com/docs/5.2/helpers#method-array-dot) with PHP equivalent functions.

Install package via composer, refer to the package using use operator

`use  \Where\Package\Installed\GoogleMaps\GoogleMaps;`

Than use as follows 

```
          $d['a'] = GoogleMaps::load('geocoding')                  
                ->setParamByKey('place_id', 'ChIJd8BlQ2BZwokRAFUEcm_qrcA')                
                ->get();
```

Regards,
Alexander

**Comment by alexpechkarev** [comment]
Forget to mention about config.php, you will need to find away around in ThinkPHP to pull config parameters.

**Comment by WongYueKeung** [comment]
okay, I will try config it, how should contribute it after it work?

**Comment by creditbigru** [comment]
@WongYueKeung Hey.
Did you get to run the class without the fraemwork?
