### ISSUE TITLE
Not returning any route in directions

### ISSUE THREAD

**Issue by luanrodrigues** [alexpechkarev/google-maps#47]
Hi there, how r u?

I'm facing a problem, when I make a few requests, for some of them i get no route. when i go to google maps and input same data, i get routes from there. can give any idea what is going on?

thank you

**Comment by alexpechkarev** [comment]
Hi @luanrodrigues,

Please can you provide an example to reproduce the error ?

**Comment by luanrodrigues** [comment]
@alexpechkarev  I ask u sorry, it was my mistake
