### ISSUE TITLE
How to show map in laravel with https://github.com/alexpechkarev/google-maps  ?

### ISSUE THREAD

**Issue by askingman** [alexpechkarev/google-maps#49]
I am workin on laravel project in which i have to integrate google maps. I am using this package https://github.com/alexpechkarev/google-maps for google maps . I install this package and get api key from https://console.developers.google.com/apis/credentials . then I just follow the usage of this package for example i write the code in my controller

$response = \GoogleMaps::load('geocoding')
        ->setParam (['address' =>'santa cruz'])
        ->get();
It giving me data in json encode formate but i dont know what i do next . How can i display maps in view blade.php . can someone please give me proper example of this package via code i will be thankfull for that thanks in advanced

**Comment by alexpechkarev** [comment]
Hi @askingman ,

In your blade you would include following to display Google Map, for more examples please refer to [Code Samples](https://developers.google.com/maps/documentation/javascript/examples/)

[Full example](https://developers.google.com/maps/documentation/javascript/examples/map-simple)
` <div id="map"></div>
<script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>`

Regards,
Alexander
