### ISSUE TITLE
Loading More than one service name at the same time

### ISSUE THREAD

**Issue by bobbymax** [alexpechkarev/google-maps#52]
Good day, so I am working on a project for a real estate agency, and to provide more information for users seeking to find an apartment I would like to add a feature were nearby locations like schools, restaurants, night clubs and so on can be shown and I have been finding it very difficult.

So here's the question, can I load more than one serviceName, and if I can, how do I get responses for each service. See example

```
$response = \GoogleMaps::load('geocoding', 'nearbysearch', placeadd)
                                ->setParamByKey('address', $property->address)
                                ->setParamByKey('latlng', [how do I reference the lat and lng here])
                                ->setParamByKey('radius', 1500)
                                ->get('results.geometry.location');
```

Note that the property address comes directly from the database dynamically. I really hope I made sense. I would need help.

**Comment by alexpechkarev** [comment]
Hi @bobbymax ,

Please see usage example below.
See [Google Maps Please Search](https://developers.google.com/places/web-service/search#PlaceSearchRequests) on accepted parameters.

`name` — A term to be matched against all content that Google has indexed for this place. Equivalent to keyword. The name field is no longer restricted to place names. Values in this field are combined with values in the keyword field and passed as part of the same search string. We recommend using only the keyword parameter for all search terms.

`type` — Restricts the results to places matching the specified type. Only one type may be specified (if more than one type is provided, all types following the first entry are ignored). List of supported [Palce Types](https://developers.google.com/places/web-service/supported_types)

`   $d =   \GoogleMaps::load('nearbysearch')
               
                ->setParam([
                    'location'  => '-33.8670522,151.1957362', // this is your $property->address
                    'radius'    => '1500', // this is your radius
                    'name'      => 'Enter Your School Name', // A term to be matched against all content that Google has indexed for this place
                    'type'      => 'school' // Only one type may be specified at a time
                ])
                ->get('results.geometry.location');
`
