### ISSUE TITLE
Get response

### ISSUE THREAD

**Issue by cgalindez122** [alexpechkarev/google-maps#56]
Hi, how can return multiples paramters? i need return name, photo, address, etc.
i tried with this
get('response.name.photo')
get('response.['name.,photo']')

but the response is all parameters.

**Comment by alexpechkarev** [comment]
Hi @cgalindez122 ,

Not sure which library you are using, so can provide you with exact answer, assume it's Place Details. Have you tried `get('response')` ? this will return you full response object.

**Comment by cgalindez122** [comment]
Hi @alexpechkarev i'm using GoogleMaps::load('textsearch') and i need return only name, photo and icon so i use get( ' results.name ' ) it's ok but if i use get( 'results.name.photo ) it's return all fields.

**Comment by alexpechkarev** [comment]
Hi @cgalindez122,

According to Text Search request[ documentation](https://developers.google.com/places/web-service/search#TextSearchRequests) response contains all available data for selected place.

Once you got the response, you can extract required data,  in the following way:

```
 $response =   \GoogleMaps::load('textsearch')
               ->setParam([
                    'query'     => 'restaurants in Lytham St Annes',
                    'radius'    => '500',
                    'types'     => 'restaurant',
                ])
                ->get();
```
`$response` - is array of places, simply extract required data.

Regards
