### ISSUE TITLE
Always get error offset

### ISSUE THREAD

**Issue by skasidej** [alexpechkarev/google-maps#57]
Have no idea what this is "unserialize(): Error at offset 0 of 40 bytes". What caused the problem of this error?

**Comment by alexpechkarev** [comment]
Hi @skasidej ,

Please can you let me know on how to reproduce the issue ?
Thanks

**Comment by skasidej** [comment]
@alexpechkarev

It's okay, just found a way to fix it. firstly laravel kept responding "Class not found". I have to clear cache config. Voila, works like magic! Thx for a fast respond tho.
