### ISSUE TITLE
Google map is not seeing as a Map but as code/coordinate

### ISSUE THREAD

**Issue by ohakubi** [alexpechkarev/google-maps#58]
I'm trying to display google map on the view. But I can't displaying it as a map.
I think I am missing something but couldn't sure what.

here it is a example of my controller and view.

```
public function map()
    {
        $response = \GoogleMaps::load('geocoding')
            ->setParam(['address' => 'tokyo'])
            ->get();
        return view('welcome', compact('response'));
    }
```
```
<div style="width: 500px; height: 500px;">

   {{ $response }}

</div>
```

what i am missing here: it returns on page like this. 

> { "results" : [ { "address_components" : [ { "long_name" : "Tokyo", "short_name" : "Tokyo", "types" : [ "administrative_area_level_1", "locality", "political" ] }, { "long_name" : "Japan", "short_name" : "JP", "types" : [ "country", "political" ] } ], "formatted_address" : "Tokyo, Japan", "geometry" : { "bounds" : { "northeast" : { "lat" : 35.8986468, "lng" : 153.9876115 }, "southwest" : { "lat" : 24.2242626, "lng" : 138.942758 } }, "location" : { "lat" : 35.6894875, "lng" : 139.6917064 }, "location_type" : "APPROXIMATE", "viewport" : { "northeast" : { "lat" : 35.817813, "lng" : 139.910202 }, "southwest" : { "lat" : 35.528873, "lng" : 139.510574 } } }, "place_id" : "ChIJ51cu8IcbXWARiRtXIothAS4", "types" : [ "administrative_area_level_1", "locality", "political" ] } ], "status" : "OK" }

**Comment by alexpechkarev** [comment]
Hi @ohakubi ,

Unfortunately this package is not displaying map, but querying Google Maps API.
If you wish to display map, please refer to [this example](https://developers.google.com/maps/documentation/javascript/tutorial#The_Hello_World_of_Google_Maps_v3) Hope this helps.

Regards

**Comment by DavidMalaba** [comment]
But how do you display data on the map based on the result your API returns?
