### ISSUE TITLE
Set API key dynamically

### ISSUE THREAD

**Issue by codificar** [alexpechkarev/google-maps#59]
Hello,

I need to obtain the API key dynamically from a database, depending on the application instance.
It cannot be obtained statically from the config file.
Are there any way to set it per API call, or dynamically set it on the config options? Thanks.

**Comment by codificar** [comment]
I have found a workaround:

\Config::set('googlemaps.key', $key);

**Comment by alexpechkarev** [comment]
Hi @codificar,

That exactly what I wanted to suggest.
Thanks,
Alexander
