### ISSUE TITLE
Address falls near another address using Lat/Long and Radius

### ISSUE THREAD

**Issue by mansouralex** [alexpechkarev/google-maps#6]
Hi, 

Actually, it's not an issue - but this is the only way I can contact you.

Does this package support the following case:

To check if an address falls within another address using Lat/Long and Radius. 

Thanks.

**Comment by alexpechkarev** [comment]
Hi mansouralex,

Unfortunately this package has no such method.
Regards,
Alexander

**Comment by mansouralex** [comment]
Thanks for your response. 

Do you know if any Google Maps API could help?

Thanks.

**Comment by alexpechkarev** [comment]
Check this article, is not exactly what you looking for, but may get you started.

https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation

**Comment by mansouralex** [comment]
Actually, I'm interested more in server side related API. Anyway Thank you.

**Comment by alexpechkarev** [comment]
You can try achieving similar with this package using method below, where origin and destination defining your search scope and lat and lng coordinates of address.

$response = \GoogleMaps::load('directions')
            ->setParam([
                'origin'          => 'place_id:ChIJ685WIFYViEgRHlHvBbiD5nE', 
                'destination'     => 'place_id:ChIJA01I-8YVhkgRGJb0fW4UX7Y', 
            ])
           ->containsLocation(55.86483,-4.25161);

    dd( $response  );  // true

Hope this helps!
Regards,
Alexander

**Comment by mansouralex** [comment]
Not sure from where I can get the place_id. Any ideas? 

The details I will be having is Lat/Long and Radius of the main address and Lat/Long for the address I will be checking if it's within the main address or not.

**Comment by alexpechkarev** [comment]
Instead of place_id you can use latitude and longitude, for both origin and destination.
origin — The address, textual latitude/longitude value, or place ID from which you wish to calculate directions.
destination — The address, textual latitude/longitude value, or place ID to which you wish to calculate directions. The options for the destination parameter are the same as for the origin parameter, described above.

https://developers.google.com/maps/documentation/directions/intro#DirectionsRequests

**Comment by mansouralex** [comment]
Thank you. I have make by calculating the distance between the two points and if the distance is less than the radius then it's inside. With the help of this package  https://github.com/toin0u/Geotools-laravel
