### ISSUE TITLE
place add service does not work

### ISSUE THREAD

**Issue by estebansolisd** [alexpechkarev/google-maps#60]
When request to google maps shows error 404 in google

**Comment by alexpechkarev** [comment]
Hi @estebansolisd,

Please can you provide an example to reproduce an error ?
Regards

**Comment by estebansolisd** [comment]
$response = \GoogleMaps::load('placeadd')
                ->setParam([
                   'location' => [
                        'lat'  => -33.8669710,
                        'lng'  => 151.1958750
                      ],
                   'accuracy'           => 0,
                   "name"               =>  "Google Shoes!",
                   "address"            => "48 Pirrama Road, Pyrmont, NSW 2009, Australia",
                   "types"              => ["shoe_store"],
                   "website"            => "http://www.google.com.au/",
                   "language"           => "en-AU",
                   "phone_number"       =>  "(02) 9374 4000"                       
                          ])
                  ->get();

**Comment by alexpechkarev** [comment]
Unfortunately this API call has been removed, see [Removing Place Add, Delete & Radar Search features](https://cloud.google.com/blog/products/maps-platform/announcing-deprecation-of-place-add)
