### ISSUE TITLE
How can i exclude results providing product_id

### ISSUE THREAD

**Issue by estebansolisd** [alexpechkarev/google-maps#61]

**Comment by alexpechkarev** [comment]
@estebansolisd please can you provide an example of the call you make?

**Comment by estebansolisd** [comment]
For example something like this:        

$response = \GoogleMaps::load('textsearch')
		->setParam (['query' => 'bar in new york')
        ->get();
        **->exclude(['product_id'=>['1214st55g','12343r5a','23244wwfa']);**

**Comment by alexpechkarev** [comment]
Hi @estebansolisd 

Please open the pull request and suggest your implementation of `exclude` method.
Alternatively, you can exclude part of the response using Laravel collection [`except()`](https://laravel.com/docs/5.4/collections#method-except) method.
