### ISSUE TITLE
Error using the Class

### ISSUE THREAD

**Issue by pablovdsp** [alexpechkarev/google-maps#62]
"count(): Parameter must be an array or an object that implements Countable"
![image](https://user-images.githubusercontent.com/4430459/53761076-62d18380-3ea3-11e9-877e-1686466c9d83.png)

**Comment by alexpechkarev** [comment]
Hi @pablovdsp,

Please ensure you use package version `1.0.9` and have published package config file

`Publish configuration file using php artisan vendor:publish --tag=googlemaps --force or simply copy package configuration file and paste into config/googlemaps.php

Open configuration file config/googlemaps.php and add your service key`

**Comment by pablovdsp** [comment]
Thanks man! This works.
Can you update that here? (1.0.8) to (1.0.9)
https://alexpechkarev.github.io/google-maps/

I'll help a lot of people.

Best Regards.

**Comment by alexpechkarev** [comment]
Thanks @pablovdsp !
The page has been updated.
