### ISSUE TITLE
Error only while testing

### ISSUE THREAD

**Issue by keliix06** [alexpechkarev/google-maps#72]
I am writing a test to make sure that I am still able to communicate with Google, and that the response looks how I expect.

This is my test
```
/** @test */
    public function a_zip_code_is_converted_to_lat_lng_correctly()
    {
        $service = new MapsService;

        $this->assertEquals(['lat' => 45.0122826, 'lng' => -93.1640525], $service->addressToLatLng('55113'));
    }
```

And this is the `addressToLatLng` method

```
public function addressToLatLng(string $address): array
    {
        $result = [
            'lat' => 0,
            'lng' => 0
        ];

        try {
            $geoResponse = \GoogleMaps::load('geocoding')
                ->setParam([
                    'address'    => $address,
                ])
                ->get('results.geometry.location');
        } catch (ErrorException $e) {
            return $result;
        }

        if (array_has($geoResponse, ['results.0.geometry.location'])) {
            $result = $geoResponse['results'][0]['geometry']['location'];
        }

        return $result;
    }
```

The code is copied from an old project.

If I use Tinkerwell I can confirm that I'm getting the response that I expect. But when I run the test I get `Class 'GoogleMaps' not found`. 

config/app.php has been updated to include `GoogleMaps\ServiceProvider\GoogleMapsServiceProvider::class,` in providers and `'GoogleMaps' => GoogleMaps\Facade\GoogleMapsFacade::class,` in aliases.

Any ideas for what I could be missing?

**Comment by alexpechkarev** [comment]
Hi @keliix06,

Please can you le me know how you executing the test?
