### ISSUE TITLE
Invalid version string ":6.0" error

### ISSUE THREAD

**Issue by PaulUgwu** [alexpechkarev/google-maps#74]
tried using composer to install the package and I got this error message in command prompt
  
[UnexpectedValueException]                                                                                                          
  Could not parse version constraint :6.0: Invalid version string ":6.0"

My project is using laravel 6.

**Comment by alexpechkarev** [comment]
Hi @PaulUgwu,

Please ensure you use following syntax to install this package
`composer require "alexpechkarev/google-maps":"6.0"`

Please note: php-curl extension must be installed and enabled in your environment.
