### ISSUE TITLE
How to catch errors related to API key?

### ISSUE THREAD

**Issue by jpmurray** [alexpechkarev/google-maps#79]
I'm having a trouble with an API key, but I can't seem to be able to catch whatever would be the response from Google. Any pointers on this?

**Comment by alexpechkarev** [comment]
Hi @jpmurray ,

Please can you show an example of the code to replicate the error?

**Comment by jpmurray** [comment]
No really, but I know I got a case where playing with the package that my API key was not the right one (ie: blocked to a specific domain which wasn't the actual one I was using).

The package returned what seemed like a general error / exception, I couldn't tell what was really happening.

**Comment by alexpechkarev** [comment]
Hi @jpmurray ,

Please could you submit a pull request suggesting the way to handle this type of issue?
Regards
