### ISSUE TITLE
Problem submitting an array of lon/lat with elevation service

### ISSUE THREAD

**Issue by paceband** [alexpechkarev/google-maps#8]
In joinParam method of Parameters.php
```
return !is_null( $allParam )
                ? implode($glue, str_replace(['%252C'],[','],$allParam) )
                :''; 
```
should be replaced by
```
return !is_null( $allParam )
                ? implode($glue, str_replace(['%7C'],['|'],str_replace(['%252C'],[','],$allParam)) )
                :'';
```
in order to managed a list of lat/lon when calling an "elevation" Google service.
This is cause be the encoding replacing "|" by the encoded value (%7C). There might be also a different way to do that.

**Comment by paceband** [comment]
Version 1.0.5 solved the problem.
You can close that issue.

**Comment by alexpechkarev** [comment]
Version 1.0.5 solved the problem.

**Comment by paceband** [comment]
The problem is still present with version 1.0.5. The pipe is still encoded so that this is required:
`str_replace(['%7C'],['|']`
