### ISSUE TITLE
I can't install in laravel7.4

### ISSUE THREAD

**Issue by mosvict** [alexpechkarev/google-maps#80]
Hi. How are you?
I am using php7.2 and laravel7.4.
I tried to install this package. But I can't install it.
I need your help.

**Comment by alexpechkarev** [comment]
Hi @mosvict,

Please can you ensure using the following to instal in Laravel 7

`composer require "alexpechkarev/google-maps":"7.0"`

Regards

**Comment by mosvict** [comment]
Thank you for your reply.
So Can't install this package in Laravel 7.4?
Should I downgrade laravel to 7.0?

https://prnt.sc/rwo4ep

**Comment by alexpechkarev** [comment]
It's working perfectly fine https://prnt.sc/rwvrpp

Try 
`composer require alexpechkarev/google-maps
`
