### ISSUE TITLE
how to return data to view (blade)

### ISSUE THREAD

**Issue by DavidMalaba** [alexpechkarev/google-maps#81]
Hi all, i m using that package in a current project and i want to know how can i return a response data and show it in the view (blade) in map

**Comment by alexpechkarev** [comment]
Hi @DavidMalaba ,

```
<script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 3,
          center: **{ PUT YOUR COORDINATES HERE }**
          mapTypeId: 'terrain'
        });
</script>
```

For more details please refer to [Google Documentation](https://developers.google.com/maps/documentation/javascript/adding-a-google-map) on how to render the API response on the map.
