### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by KasunAssetDidital** [alexpechkarev/google-maps#82]
Hi alexpechkarev,

I found that your library is very useful how ever there is an issue when use Direction api, i got following error,if you can please help me with that

**my PHP Version 7.4.2**

![bandicam 2020-05-19 20-02-13-856](https://user-images.githubusercontent.com/64188066/82339621-db225700-9a0b-11ea-8f70-f10fccd788bc.jpg)

error generating from this **$b** variable

![bandicam 2020-05-19 20-03-27-067](https://user-images.githubusercontent.com/64188066/82339730-fd1bd980-9a0b-11ea-9c48-5407c113c732.jpg)

Thank you

**Comment by KasunAssetDidital** [comment]
i found the issue need to replace on line 339,349 `{$index++}` with `[index++]`

**Comment by alexpechkarev** [comment]
Hi @KasunAssetDidital 

Thank you for pointing out.

This package was referencing to an older version of `geometry-library`, have updated and published a new release `7.1`.

`composer require "alexpechkarev/google-maps":"7.1"`

Regards

**Comment by martin-arvisais** [comment]
Hi, are you planning to do the same update to the version 6.0 (for Laravel 6.X), i have the same problem, but i must stay on a Laravel 6.x version, thx :)
