### ISSUE TITLE
Waypoint Not working properly 

### ISSUE THREAD

**Issue by KasunAssetDidital** [alexpechkarev/google-maps#84]
Hi @alexpechkarev 

I'm using your package its very use full however when I try to get route using directions API in some cases its returns `{ "routes": [], "status": "ZERO_RESULTS" }` after adding a waypoints

here is my code 
           ` $response = $map->load('directions')->setParam([
            'origin' => $request->from,
            'destination' => $request->to,
            'mode' => 'driving',
            'avoid' => $user->avoids(),
            'waypoints' => $waypoints 
            ])->get();`

`$waypoints = ['optimize:true','Nottingham, United Kingdom']`

if I comment `'waypoints' => $waypoints ` then it's working, what I missed here   updated your package new version 7.1 

here is my previous [issue](https://github.com/alexpechkarev/google-maps/issues/82)

could you help me 
thank you

**Comment by KasunAssetDidital** [comment]
Hi @alexpechkarev 

problem is the way we deliver waypoints

`$response = $map->load('directions')->setParam([ 
                                        'origin' => $request->from,
                                        'destination' => $request->to,
                                        'mode' => 'driving',
                                        'avoid' => $user->avoids(),`
                                        **'waypoints' => $waypoints**
                                      `])->get();`

if I provide waypoints as a string it's works
`'waypoints' => 'optimize:true|Nottingham, United Kingdom|Oxford, United Kingdom'` 

but if I deliver waypoint as an array it's not works
`'waypoints' => ['optimize:true','Nottingham, United Kingdom','Oxford, United Kingdom']`
can you tell me how I provide array of waypoint

**Comment by alexpechkarev** [comment]
Hi @KasunAssetDidital,

Apologies for the late response.
I guess you will need to convert your array to string before submitting the request.

```php
'waypoints' => implode("|",['optimize:true','Nottingham, United Kingdom','Oxford, United Kingdom']);
```

Regards,
Alexander
