### ISSUE TITLE
Input options values transliteration is redundant as cause incorrect result.

### ISSUE THREAD

**Issue by just-greg-me** [alexpechkarev/google-maps#87]
The issue I've faced, is that if `input` params option contains cyrillic alphabet, they are transliterated and encoded in wrong way.

E.g.: `Полтава, ул. Пушкина 64а` will cause the result that won't be processed further, because the input will be transformed not like expected `Полтава%20ул%20Пушкина%2064а` but in `Poltava+ul+Puskina+64a` that is incorrect.

But, the `Poltava Pushkin str 64a` value will work as expected.

Actually, the wrong input processing is in `alexpechkarev/google-maps/src/Parameters.php` class, on line 119

**Comment by alexpechkarev** [comment]
Hi @just-greg-me,

Thank you for your message and apologies for the late response.

Please could you suggest the solution to resolve this issue?

**Comment by just-greg-me** [comment]
@alexpechkarev I think, the URLify downcode could be replaced, as it's required from the package user to ensure the content encoding is correct, and as well, Google Maps supports plenty languages, so it's not so vital to transliterate all the values into an english.
