### ISSUE TITLE
Elevetion service with a long list a value is rejected by Google

### ISSUE THREAD

**Issue by paceband** [alexpechkarev/google-maps#9]
This request works (replace MYKEY with your key) :
`https://maps.googleapis.com/maps/api/elevation/json?key=<MYKEY>&locations=45.523720,-73.538790|45.524540,-73.538650|45.525100,-73.538500|45.525840,-73.538200|45.526270,-73.537990|45.526920,-73.537570|45.527280,-73.537310|45.527740,-73.536910|45.528110,-73.536650|45.529090,-73.535880|45.529040,-73.535120|45.528870,-73.532620|45.529050,-73.535320|45.529080,-73.535780|45.527880,-73.536690|45.527810,-73.536730|45.527720,-73.536760|45.527630,-73.536720|45.527310,-73.536590|45.526910,-73.536390|45.526880,-73.536330|45.527060,-73.535700|45.527060,-73.535580|45.526960,-73.534920|45.526930,-73.534840|45.526840,-73.534710|45.526690,-73.534610|45.526620,-73.534470|45.526540,-73.534240|45.526470,-73.534200|45.525940,-73.534040|45.525890,-73.534030|45.525850,-73.533860|45.525800,-73.533690|45.525520,-73.533220|45.525000,-73.532430|45.524840,-73.532130|45.524720,-73.532010|45.524660,-73.531970|45.524540,-73.531930|45.524410,-73.531900|45.524060,-73.531880|45.523010,-73.531880|45.522120,-73.531790|45.521760,-73.531770|45.519710,-73.531480|45.519300,-73.531390|45.519220,-73.531360|45.518860,-73.531150|45.518770,-73.531150|45.518470,-73.531030|45.518210,-73.530900|45.518050,-73.530850|45.517740,-73.530780|45.517070,-73.530650|45.515930,-73.530420|45.515610,-73.530350|45.515340,-73.530260|45.515080,-73.530170|45.514860,-73.530150|45.514530,-73.530170|45.514230,-73.530260|45.514090,-73.530320|45.513680,-73.530570|45.513400,-73.530690|45.512990,-73.530790|45.512960,-73.530800|45.512990,-73.530790|45.512990,-73.530570|45.512970,-73.527880|45.512150,-73.527880|45.511710,-73.527930|45.511320,-73.528020|45.510890,-73.528130|45.510350,-73.528340|45.509720,-73.528620|45.509510,-73.528640|45.509260,-73.528630|45.509010,-73.528570|45.508880,-73.528490|45.508810,-73.528440|45.508790,-73.528420|45.508910,-73.528270|45.509000,-73.528180|45.509230,-73.528060|45.509610,-73.527900|45.510240,-73.527660|45.511060,-73.527430|45.511630,-73.527300|45.512040,-73.527270|45.512300,-73.527270|45.512530,-73.527280|45.512750,-73.527320|45.513640,-73.527570|45.514100,-73.527700|45.514180,-73.527690|45.514240,-73.527640|45.514260,-73.527610|45.514290,-73.527550|45.514300,-73.527480|45.514280,-73.527390|45.514240,-73.527290|45.514120,-73.527220|45.513730,-73.527150|45.513450,-73.527130|45.513320,-73.527100|45.513120,-73.527010|45.512410,-73.526530|45.510260,-73.525350|45.510010,-73.525240|45.507920,-73.524610|45.503920,-73.523440|45.503340,-73.523240|45.503330,-73.523240|45.503170,-73.523240|45.502740,-73.523330|45.502630,-73.523320|45.499710,-73.522440|45.499390,-73.522390|45.499260,-73.522380|45.499110,-73.522390|45.498950,-73.522370|45.497700,-73.521990|45.497480,-73.521950|45.497280,-73.521940|45.497160,-73.522020|45.497070,-73.522170|45.497040,-73.522430|45.497070,-73.522760|45.497150,-73.523200|45.497350,-73.523970|45.497450,-73.524220|45.497670,-73.524640|45.498750,-73.526350|45.499130,-73.526840|45.499480,-73.527220|45.500010,-73.527730|45.500440,-73.528090|45.501280,-73.528710|45.501640,-73.528960|45.502180,-73.529240|45.502720,-73.529470|45.502890,-73.529540|45.503720,-73.529780|45.503940,-73.529820|45.504830,-73.529910|45.505530,-73.529940|45.505790,-73.529920|45.506590,-73.529820|45.507130,-73.529680|45.507790,-73.529440|45.508560,-73.529130|45.508497,-73.528748|45.508151,-73.528748|45.507956,-73.528962|45.508016,-73.529842|45.508250,-73.531550|45.508340,-73.532220|45.508370,-73.532550|45.508390,-73.532680|45.508380,-73.532810|45.508370,-73.532930|45.508300,-73.533130|45.508240,-73.533190|45.507880,-73.534260|45.507500,-73.535290|45.507280,-73.535900|45.504900,-73.542340|45.504900,-73.542490|45.504740,-73.542920|45.504550,-73.543390|45.504390,-73.543660|45.504210,-73.543850|45.504020,-73.543970|45.503890,-73.544020|45.503740,-73.544040|45.503580,-73.544060|45.503510,-73.544060|45.503410,-73.544010|45.502160,-73.544140|45.500040,-73.544380|45.497820,-73.544650`
fails.
It looks like Google does not accept more than 2048 characters as parameters.
It would by nice if your library could break the request into many requests and returns the concatenated request so the this limitation would by hidden from the caller.
Or any other way to bybass the limitation properly?
Thanks

**Comment by paceband** [comment]
Version 1.0.5 solved the problem. In 1.0.4 pipe was encoded "%7C".
You can close that issue.

**Comment by alexpechkarev** [comment]
Version 1.0.5 solved the problem.

**Comment by paceband** [comment]
Version 1.0.5 does not solve the problem.
Please read my first post which I updated yesterday.
I solution I did locally is, at, least, to call the Google API 10 times in a row and passing a maximum of 80 values. I think that around 95 lat/lon was still ok but I want some security.
Google fix a maximum of 10 calls per seconds.
This logic may be applied to other Google services which I do not use.
Thanks
