### ISSUE TITLE
How can I pass response into view blade file In laravel 8?

### ISSUE THREAD

**Issue by Keshabpal9933** [alexpechkarev/google-maps#91]

**Comment by alexpechkarev** [comment]
Hi @Keshabpal9933,

Depending on the structure of your application, I guess you can do the following in your Controller


  public function show($id)
    {

      $response = \GoogleMaps::load('geocoding')
		      ->setParam (['address' =>'santa cruz'])
 		      ->get();

        return view('map', compact('resposne) );
    }



Regards,
Alexander
