### ISSUE TITLE
Does this class , record maps into cache ?

### ISSUE THREAD

**Issue by murilolivorato** [alexpechkarev/google-maps#92]
Hello , I recently have seen this vide tutorial .
https://www.youtube.com/watch?v=LTJ5t3fXoXU&t=157s
It shoes this class -
https://github.com/farhanwazir/laravelgooglemaps
that record the map into cache ( mysql ) , and It not make a new request to google . so you dont need to make new request to google aways you look for map .
does this class make the same ? it is that possible ? I wold like to use your class . thanks

**Comment by alexpechkarev** [comment]
Hi @murilolivorato,

Thank you for your feedback.

You can cache the responses and re-use them for subsequent requests, but I am afraid this is outside of the scope of this project. Fill free to open the pull request and suggest your changes.

Regards,
Alexander
