### ISSUE TITLE
Possible better exception message

### ISSUE THREAD

**Issue by eddimull** [alexpechkarev/google-maps#93]
Hello, I am just getting started using your package and the Google api system. I made a typo on requesting the service. I inputted 'geocode' instead of 'geocoding'. My question is, would it be possible to add in the $service variable that is being requested in the validateConfig method? The exception: 'Web service must be declared in the configuration file.' made it seem like Laravel wasn't registering the whole service provider instead of just not being able to access the non-existent 'geocode'. 

Thanks!

**Comment by alexpechkarev** [comment]
Hi @eddimull,

Thank you for your feedback.

Please open the pull request with the proposed change?

Regards,
Alexander
