### ISSUE TITLE
Always get only one alternative Route

### ISSUE THREAD

**Issue by mreduar** [alexpechkarev/google-maps#96]
Hi, I am trying to get all the alternative routes between two points with coordinates, but I always get only one route even though I am sending `alternatives=true` in the request parameters.

Let me give you an example.

In this [link](https://maps.googleapis.com/maps/api/directions/json?origin=10.0631549,-69.3103233&destination=10.0540698,-69.3421256&alternatives=true&key=YOUR_KEY) You will get three routes in total, the main route and two alternative routes.
![image](https://user-images.githubusercontent.com/22550119/130630328-86b48eeb-b50e-44b7-85b5-495f2375cebf.png)

But when I do it with your package I always get only one route.
![image](https://user-images.githubusercontent.com/22550119/130630192-58335c27-4488-463e-898a-5ab47658de0d.png)

This is the code I am using to get the alternate routes with your package.
```php
$origins = ['10.0631549', '-69.3103233'];
$destinations = ['10.0540698', '-69.3421256'];

$response = \GoogleMaps::load('directions')
              ->setParam([
                  'origin' => implode(',', $origins),
                  'destination' => implode(',', $destinations),
                  'alternatives' => true,
                  'language' => 'es'
              ])->get();
```

What do I have to do to get the alternative routes with your package?

**Comment by alexpechkarev** [comment]
Hi @mreduar 

Apologies for the late response and thank you for pointing out.
It appears to be that the `alternatives` value has been send as integer instead of boolean, this has been corrected now.
